"""
Data Schemas for AI-Powered Mobile Urban Intelligence Platform (Nagar Drishti)
Defines Pydantic v2 schemas for Edge-to-Cloud telemetry, ANPR events,
spatial clustering results, and automated agentic municipal work orders.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict


class DefectCategory(str, Enum):
    POTHOLE = "POTHOLE"
    ROAD_CRACK = "ROAD_CRACK"
    DAMAGED_DIVIDER = "DAMAGED_DIVIDER"
    MISSING_ZEBRA_CROSSING = "MISSING_ZEBRA_CROSSING"
    DAMAGED_TRAFFIC_SIGN = "DAMAGED_TRAFFIC_SIGN"
    WATERLOGGING = "WATERLOGGING"
    BLIND_SPOT_PEDESTRIAN = "BLIND_SPOT_PEDESTRIAN"
    CABIN_MISCONDUCT = "CABIN_MISCONDUCT"


class SeverityLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class CameraChannel(str, Enum):
    FRONT = "FRONT"
    REAR = "REAR"
    LEFT_SIDE = "LEFT_SIDE"
    RIGHT_SIDE = "RIGHT_SIDE"
    CABIN_INTERIOR = "CABIN_INTERIOR"


class GPSCoordinate(BaseModel):
    latitude: float = Field(..., ge=-90.0, le=90.0, description="WGS84 Latitude in decimal degrees")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="WGS84 Longitude in decimal degrees")
    altitude_m: Optional[float] = Field(default=None, description="Altitude in meters")
    heading_deg: Optional[float] = Field(default=None, ge=0.0, le=360.0, description="Heading in degrees from true North")
    speed_kmh: float = Field(default=0.0, ge=0.0, description="Instantaneous vehicle speed in km/h")
    accuracy_m: float = Field(default=2.5, description="Horizontal GPS dilution of precision in meters")


class BoundingBox(BaseModel):
    x_min: float = Field(..., ge=0.0, le=1.0, description="Normalized Top-Left X (0.0 - 1.0)")
    y_min: float = Field(..., ge=0.0, le=1.0, description="Normalized Top-Left Y (0.0 - 1.0)")
    x_max: float = Field(..., ge=0.0, le=1.0, description="Normalized Bottom-Right X (0.0 - 1.0)")
    y_max: float = Field(..., ge=0.0, le=1.0, description="Normalized Bottom-Right Y (0.0 - 1.0)")


class DetectedDefect(BaseModel):
    detection_id: str = Field(..., description="Unique UUID for this specific visual detection")
    category: DefectCategory
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model inference confidence score")
    bbox: BoundingBox
    segmentation_polygon: Optional[List[List[float]]] = Field(default=None, description="Polygon contour coordinates if instance segmented")
    estimated_depth_cm: Optional[float] = Field(default=None, description="Stereo / monocular estimated defect depth in cm")
    estimated_area_sqm: Optional[float] = Field(default=None, description="Calculated surface area in square meters")


class ANPREvent(BaseModel):
    track_id: int = Field(..., description="ByteTrack continuous object tracking ID")
    license_plate_text: str = Field(..., description="Normalized alphanumeric license plate string")
    plate_confidence: float = Field(..., ge=0.0, le=1.0, description="OCR character confidence score")
    vehicle_class: str = Field(default="car", description="Classified vehicle type (car, hgv, bike, bus)")
    violation_type: Optional[str] = Field(default=None, description="Violations like bus_lane_encroachment, rash_overtaking")
    speed_estimate_kmh: Optional[float] = Field(default=None, description="Tracked optical flow speed estimation in km/h")
    cropped_plate_thumbnail_b64: Optional[str] = Field(default=None, description="Base64 JPEG thumbnail of cropped license plate")


class EdgeTelemetryPayload(BaseModel):
    """
    Lightweight JSON message dispatched from bus edge hardware to MQTT broker.
    Bandwidth compressed: sends metadata + low-overhead cropped snapshot thumbnails only on detected events.
    """
    model_config = ConfigDict(extra="ignore")

    message_id: str = Field(..., description="UUID v4 message identifier")
    bus_node_id: str = Field(..., description="Public transport bus hardware ID, e.g. DTC-BUS-402")
    route_id: str = Field(..., description="Assigned public transit route identifier")
    timestamp_iso: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    camera_channel: CameraChannel
    gps: GPSCoordinate
    defects: List[DetectedDefect] = Field(default_factory=list)
    anpr_events: List[ANPREvent] = Field(default_factory=list)
    event_snapshot_thumbnail_b64: Optional[str] = Field(default=None, description="WebP / JPEG compressed thumbnail of keyframe")
    edge_device_health: Dict[str, Any] = Field(
        default_factory=lambda: {
            "gpu_temp_c": 54.2,
            "inference_fps": 31.4,
            "latency_ms": 18.2,
            "storage_remaining_gb": 42.8
        }
    )


class SpatialClusterDefect(BaseModel):
    """
    Aggregated defect output generated by Cloud DBSCAN spatial clustering
    across multiple bus passes over time.
    """
    cluster_id: str = Field(..., description="Consolidated cluster identifier, e.g. CLUSTER-RINGRD-042")
    category: DefectCategory
    centroid_gps: GPSCoordinate
    detection_count: int = Field(..., description="Number of distinct buses that detected this defect")
    first_detected_iso: str
    last_detected_iso: str
    contributing_bus_ids: List[str]
    aggregate_confidence: float = Field(..., ge=0.0, le=1.0)
    calculated_severity: SeverityLevel
    verified_by_secondary_cloud_ai: bool = Field(default=True)
    representative_snapshot_url: str


class MunicipalWorkOrder(BaseModel):
    """
    Automated work order synthesized by Agentic LLM Dispatcher
    """
    work_order_id: str
    cluster_id: str
    title: str
    department_assigned: str
    severity: SeverityLevel
    target_sla_hours: int
    sla_deadline_iso: str
    location_landmark: str
    ward: str
    recommended_repair_procedure: str
    materials_estimated: List[str]
    evidence_image_url: str
    status: str = Field(default="AUTO_DISPATCHED")
    created_at_iso: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
